# Generated by Django 4.2.5 on 2024-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'admin'), ('U', 'user')], default='U', max_length=1),
        ),
    ]
