# Generated by Django 4.2.5 on 2024-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Fruits'), ('B', 'Beverage'), ('V', 'Vegetables'), ('O', 'Other')], default='V', max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
