# Generated by Django 4.2.5 on 2024-07-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
